# Generated by Django 6.0.5 on 2026-06-04 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_remove_profile_badge_remove_profile_xp_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('best_season_json', models.TextField(default='{}', help_text='JSON: {"Jan":"green","Feb":"yellow",...}')),
                ('crowd_level', models.CharField(default='moderate', max_length=20)),
                ('safety_rating', models.PositiveSmallIntegerField(default=4)),
                ('budget_tier', models.CharField(default='$$', max_length=4)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
                ('getting_there', models.TextField(blank=True)),
                ('local_transport', models.TextField(blank=True)),
                ('must_visit_spots', models.TextField(blank=True)),
                ('local_food', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('estimated_budget_per_day', models.CharField(blank=True, max_length=60)),
                ('language_tips', models.TextField(blank=True)),
                ('emergency_numbers', models.TextField(blank=True)),
                ('tourist_office_contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bucket_list', 'Bucket List'), ('dream_trips', 'Dream Trips'), ('visited', 'Visited'), ('favorites', 'Favorites')], default='favorites', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_expertise', models.TextField(blank=True, default='[]', help_text='JSON list of cities, e.g. ["Ooty","Kodaikanal"]')),
                ('languages', models.CharField(blank=True, default='English', max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(default=1)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('total_tours', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('availability_status', models.BooleanField(default=True)),
                ('response_time', models.CharField(default='Within an hour', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-total_tours'],
            },
        ),
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('budget', models.CharField(blank=True, max_length=80)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('days_count', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('time_block', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=15)),
                ('activity', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='social.itinerary')),
            ],
            options={
                'ordering': ['day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='social.collection')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='social.post')),
            ],
            options={
                'unique_together': {('collection', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('love', '❤️ Love'), ('wow', '🤩 Wow'), ('haha', '😂 Haha'), ('sad', '😢 Sad'), ('fire', '🔥 Fire')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
