# Generated by Django 6.0.5 on 2026-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_destination_collection_guideprofile_guiderequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social.profile',),
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='budget_per_day',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='how_to_reach',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='language_tip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='destinations',
            field=models.TextField(blank=True, help_text='Comma-separated cities'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=8),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='countries_visited',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='reel',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reels/'),
        ),
    ]
