# Generated by Django 6.0.5 on 2026-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_userprofile_remove_guideprofile_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
