# Generated by Django 6.0.5 on 2026-06-04 14:47

from django.db import migrations


def seed_chat_rooms(apps, schema_editor):
    ChatRoom = apps.get_model('social', 'ChatRoom')
    defaults = [
        {'name': 'Global Travelers', 'slug': 'global-travelers', 'room_type': 'global', 'icon': '🌍', 'description': 'Chat with travelers from around the world', 'is_default': True},
        {'name': 'Solo Travelers', 'slug': 'solo-travelers', 'room_type': 'solo', 'icon': '🎒', 'description': 'Tips, stories and advice for solo adventurers', 'is_default': True},
        {'name': 'Backpackers', 'slug': 'backpackers', 'room_type': 'backpacker', 'icon': '🏕️', 'description': 'Budget travel hacks, hostel recommendations and backpacking routes', 'is_default': True},
        {'name': 'Europe Travel', 'slug': 'europe-travel', 'room_type': 'country', 'icon': '🇪🇺', 'description': 'Discuss European destinations, rail passes and hidden gems'},
        {'name': 'Southeast Asia', 'slug': 'southeast-asia', 'room_type': 'country', 'icon': '🌏', 'description': 'Explore Thailand, Vietnam, Indonesia and more'},
        {'name': 'South America', 'slug': 'south-america', 'room_type': 'country', 'icon': '🌎', 'description': 'Adventure across Patagonia, Amazon, Andes and beyond'},
    ]
    for data in defaults:
        ChatRoom.objects.get_or_create(slug=data['slug'], defaults=data)


def remove_chat_rooms(apps, schema_editor):
    ChatRoom = apps.get_model('social', 'ChatRoom')
    ChatRoom.objects.filter(slug__in=[
        'global-travelers', 'solo-travelers', 'backpackers',
        'europe-travel', 'southeast-asia', 'south-america',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_chatroom_chatmessage_communityevent_travelgroup_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_chat_rooms, remove_chat_rooms),
    ]
