# Generated by Django 6.0.5 on 2026-06-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_is_public_post_video_profile_is_public'),
        ('social', '0011_seed_default_chat_rooms'),
    ]

    operations = [
    ]
