# Generated by Django 6.0.5 on 2026-06-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_reel_options_remove_post_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reel_comments', to='social.reel'),
        ),
    ]
